# Generated by Django 6.0.4 on 2026-04-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_chain_group_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('separation_distance', models.PositiveSmallIntegerField(default=1)),
                ('cross_event_separation', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_groups', to='accounts.broadcaster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_chain_match_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('match_date', models.DateTimeField()),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'Open'), (2, 'Active'), (3, 'Completed'), (4, 'Cancelled')], default=0)),
                ('create_tx_hash', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='accounts.broadcaster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExclusionGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_memberships', to='accounts.brand')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='matches.exclusiongroup')),
            ],
            options={
                'unique_together': {('group', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='MatchEventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(0, 'Over Break'), (1, 'Strategic Timeout'), (2, 'Innings Break'), (3, 'Wicket Fall'), (4, 'High Value Wicket'), (5, 'Last Over Thriller'), (6, 'Hat Trick Ball'), (7, 'Super Over')])),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reservation_fee_pct', models.DecimalField(decimal_places=2, max_digits=4)),
                ('slot_count', models.PositiveSmallIntegerField(default=3)),
                ('max_triggers', models.PositiveSmallIntegerField(default=40)),
                ('trigger_count', models.PositiveSmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_configs', to='matches.match')),
            ],
            options={
                'unique_together': {('match', 'event_type')},
            },
        ),
    ]
