# Generated by Django 6.0.4 on 2026-04-14 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(default=datetime.datetime(2026, 4, 14, 15, 2, 1, 711096, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(),
        ),
    ]
