# Generated by Django 6.0.4 on 2026-04-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField()),
                ('trigger_number', models.PositiveSmallIntegerField()),
                ('slot_position', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creative_ref', models.CharField(max_length=500)),
                ('tx_hash', models.CharField(max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_results', to='matches.match')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_wins', to='accounts.brand')),
            ],
            options={
                'ordering': ['event_type', 'trigger_number', 'slot_position'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reservation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='accounts.brand')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creative_ref', models.CharField(max_length=500)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='accounts.brand')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('match', 'brand', 'event_type')},
            },
        ),
    ]
