# Generated by Django 6.0.4 on 2026-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_add_creative_model_update_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='cancel_tx_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
