# Generated by Django 6.0.4 on 2026-04-14 14:16

import apps.accounts.models.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='broadcaster',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.storage.brand_logo_upload_path),
        ),
        migrations.AddField(
            model_name='broadcaster',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.storage.broadcaster_logo_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.storage.user_profile_upload_path),
        ),
    ]
